name: IVFToday
options:
  bundleIdPrefix: com.zhzhq888art
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  organizationName: LittleGoals
targets:
  IVFToday:
    type: application
    platform: iOS
    bundleId: com.zhzhq888art.ivftoday
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
    scheme:
      testTargets:
        - IVFTodayTests
        - IVFTodayUITests
    sources:
      - path: IVFToday
    resources:
      - path: IVFToday/Resources
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: SwiftData.framework
      - sdk: UIKit.framework
    info:
      path: IVFToday/Info.plist
      properties:
        CFBundleDisplayName: IVFToday
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    entitlements:
      path: IVFToday/IVFToday.entitlements
  IVFTodayTests:
    type: bundle.unit-test
    platform: iOS
    bundleId: com.zhzhq888art.ivftodayTests
    sources:
      - path: IVFTodayTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: IVFToday

  IVFTodayUITests:
    type: bundle.ui-testing
    platform: iOS
    bundleId: com.zhzhq888art.ivftodayUITests
    sources:
      - path: IVFTodayUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: IVFToday
